core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

news/urls.py
from django.urls import path
from news.views import news_list, news_in_category, news_items, like_or_dislike

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    path('<int:news_pk>/', news_items, name='news_items'),
    path('<int:news_pk>/<int:comment_pk>/<str:vote>', like_or_dislike, name='like_or_dislike'),
    path('<slug>/', news_in_category, name='news_in_category'),
]

system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

users/urls.py
from django.urls import path
from users.views import login, register, profile, logout

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

news/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    title = models.CharField(
        max_length=64,
        verbose_name='Title',
    )
    slug = models.SlugField(
        unique=True,
    )

    def __str__(self):
        return f'{self.title}'


class News(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='Category',
    )
    title = models.CharField(
        max_length=88,
        verbose_name='Title',
    )
    text = models.TextField(
        verbose_name='Text'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Published date'
    )
    main_image = models.ImageField(
        upload_to='news',
        verbose_name='Main image'
    )

    def __str__(self):
        return f'{self.title}'


class Comments(models.Model):
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='Replies',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Author',
        related_name='Comments'
    )
    article = models.ForeignKey(
        News,
        on_delete=models.CASCADE,
        related_name='Comments',
        verbose_name='Article'
    )
    text = models.TextField(
        verbose_name='Text',
    )
    created_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created date',
    )
    comment_like = models.IntegerField(
        verbose_name='Like',
        default=0,
    )
    comment_dislike = models.IntegerField(
        verbose_name='Dislike',
        default=0,
    )

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return f'{self.author}, {self.text}'


class Like(models.Model):
    VOTES = (
       ('LIKE', 'like'),
       ('DISLIKE', 'dislike'),
       (None, 'None'),
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='User',
        related_name='Like',
    )
    comment = models.ForeignKey(
        Comments,
        on_delete=models.CASCADE,
        verbose_name='Comment',
        related_name='Like',
    )
    like_or_dislike = models.CharField(
        max_length=7,
        choices=VOTES,
        default=None
    )

    def __str__(self):
        return f'{self.like_or_dislike}'

news/forms.py
from django import forms

from news.models import Comments


class CommentForm(forms.ModelForm):
    # text = SummernoteWidget()

    class Meta:
        model = Comments
        fields = (
            'text',
        )
        widgets = {
            'text': forms.Textarea(attrs={'cols': 75, 'rows': 1})
        }

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from news.models import Category, News, Comments, Like
from users.models import User
from news.forms import CommentForm


def category():
    category = Category.objects.all()
    return category


def news_list(request):
    news = News.objects.all().order_by('-published_date')
    context = {
        'news': news,
        'categories': category(),
    }
    return render(request, 'news/news_list.html', context)


def news_in_category(request, slug):
    cat = Category.objects.get(slug=slug)
    news = News.objects.filter(category=cat).order_by('-published_date')
    context = {
        'news': news,
        'categories': category(),
    }
    return render(request, 'news/news_list.html', context)


def create_comment(request, item):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_obj = Comments.objects.get(id=parent_id)
            if parent_obj:
                replay_comment = comment_form.save(commit=False)
                replay_comment.parent = parent_obj
        new_comment = comment_form.save(commit=False)
        new_comment.article = item
        new_comment.author = request.user
        new_comment.save()
        return new_comment


def like_or_dislike(request, news_pk, comment_pk, vote):
    items = get_object_or_404(News, pk=news_pk)
    comment = get_object_or_404(Comments, pk=comment_pk)
    old_like = Like.objects.filter(user=request.user, comment=comment_pk)
    if old_like:
        like = Like.objects.get(user=request.user, comment=comment_pk)
        if like.like_or_dislike == 'like' and vote == 'like':
            like.delete()
            comment.comment_like -= 1
            comment.save()
        elif like.like_or_dislike == 'dislike' and vote == 'dislike':
            like.delete()
            comment.comment_dislike -= 1
            comment.save()
        elif like.like_or_dislike == 'like' and vote == 'dislike':
            like.like_or_dislike = 'dislike'
            like.save()
            comment.comment_dislike += 1
            comment.comment_like -= 1
            comment.save()
        elif like.like_or_dislike == 'dislike' and vote == 'like':
            like.like_or_dislike = 'like'
            like.save()
            comment.comment_dislike -= 1
            comment.comment_like += 1
            comment.save()
    else:
        new_like = Like.objects.create(
            user=request.user,
            comment=comment,
            like_or_dislike=vote,
        )
        new_like.save()
        if vote == 'like':
            comment.comment_like += 1
            comment.save()
        elif vote == 'dislike':
            comment.comment_dislike += 1
            comment. save()
    return redirect('news:news_items', news_pk=items.pk)


def news_items(request, news_pk):
    items = get_object_or_404(News, pk=news_pk)
    comments = Comments.objects.filter(article=news_pk)
    best_comment = None
    for i in comments:
        if i.comment_like > 0:
            best_comment = comments.order_by('-comment_like').first()
    if request.method == 'POST':
        create_comment(request, items)
        return redirect('news:news_items', news_pk=items.pk)
    else:
        comment_form = CommentForm()
    context = {
        'items': items,
        'categories': category(),
        'comments': comments,
        'comment_form': comment_form,
        'best_comment': best_comment,
    }
    return render(request, 'news/news_items.html', context)

news/templates/news/news_items.html
{% extends 'core/base.html' %}

{% load static %}


{% block content %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

<meta name="twitter:dnt" content="on" xmlns="http://www.w3.org/1999/html">
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="{% static 'news/css/news.css' %}" type="text/css" rel="stylesheet" media="all">

<nav class="navbar navbar-expand-lg navbar-down bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler ml-md-auto" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <a class="nav-link" href="{% url 'news:news_list'  %}">
                    Вернуться
                </a>
                <a class="nav-link" href="{% url 'news:all_news' %}">
                    Все новости
                </a>

                {% for i in categories %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:news_in_category' i.slug %}">
                            {{ i.title }}
                        </a>
                {% endfor %}

                </li>
            </ul>
        </div>
    </div>
</nav>
<br>

<div class="news_page_item">
    <h2 style="text-align: center;">{{ items.title }}</h2></br>
    {{ items.text|safe }}</br>
    <div style="background-color: white;">
        <!-- Comment with nested comments -->
        <a name="log"></a>

        <h2 id="discussion">ОБСУЖДЕНИЕ</h2>
        <br>
        <div style="margin-right: 540px;">
            <div class="comment_divider"></div>

                {% if best_comment is not None %}
                    <img src="{{MEDIA_URL}}{{best_comment.author.image.url}}" alt="..." class="prof_pic"/>
                    <div  class="best_comment">
                        <div class="like_or_dislike">
                            <img class="dislike" src="{% static 'news/images/Dislike.png' %}" alt="..."/>
                            <p class="dislike_counter">{{ best_comment.comment_dislike }}</p>
                            <img class="like" src="{% static 'news/images/Like.png' %}" alt="..."/>
                            <p class="like_counter">{{ best_comment.comment_like }}</p>
                        </div>
                        <p class="info" style="margin-bottom: 0;">{{ best_comment.author }}</p>
                        <p class="info" style="margin-bottom: 0;">{{ best_comment.text|safe }}</p>
                        <p style="font-size: 14px; margin-bottom: 1;"> {{ best_comment.created_date }}</p>
                        <div>
                            <img class="best_com_img" src="{% static 'news/images/Best.jpg' %}" alt="..."/>
                            <h6 class="best_com">Лучший комментарий</h6>
                        </div>
                    </div>
                {% endif %}
            <div class="comment_divider"></div>
            {% if user.is_authenticated %}
                {% csrf_token %}


                    <div class="comment-form" id="comment-form">
                        <div class="reply-form-wrap">
                            <form action="." method="post" style="display: flex; width: 100%">
                                {% csrf_token %}
                                <textarea class="summernote" name="text" cols="21" rows="4" required="" id="first_summernote"></textarea>
                                <style>
                                    iframe.note-fullscreen {
                                        position: fixed;
                                        top: 0;
                                        left: 0;
                                        width: 100vw!important;
                                        height: 100vh!important;
                                        z-index: 4000;
                                    }
                                </style>
                                <div style="padding-left: 10px;">
                                    <input class="btn btn-primary" type="submit" value="Высказатсья">
                                </div>
                            </form>
                        </div>
                    </div>


            {% else %}
                <p>
                    Чтобы оставить свое мнение, необходимо
                    <a href="{% url 'users:login' %}">войти</a> или
                    <a href="{% url 'users:register' %}">зарегистрироваться</a>
                </p>
            {% endif %}
            </br>

            {% for comment in comments %}

                {% if comment.parent is None %}
                    <img src="{{MEDIA_URL}}{{comment.author.image.url}}" alt="..." class="prof_pic"/>
                    <div  class="comment">
                        {% if user.is_authenticated %}
                            <div class="like_or_dislike">
                                <a href="{% url 'news:like_or_dislike' news_pk=items.pk comment_pk=comment.pk vote='dislike' %}">
                                    <img class="dislike" src="{% static 'news/images/Dislike.png' %}" alt="..."/>
                                <p class="dislike_counter">{{ comment.comment_dislike }}</p>
                                </a>
                                <a href="{% url 'news:like_or_dislike' news_pk=items.pk comment_pk=comment.pk vote='like' %}">
                                    <img class="like" src="{% static 'news/images/Like.png' %}" alt="..."/>
                                <p class="like_counter">{{ comment.comment_like }}</p>
                                </a>
                            </div>
                        {% else %}
                            <div class="like_or_dislike">
                                <a href="#log">
                                    <img class="dislike" src="{% static 'news/images/Dislike.png' %}" alt="..."/>
                                    <p class="dislike_counter">{{ comment.comment_dislike }}</p>
                                </a>
                                <a href="#log">
                                    <img class="like" src="{% static 'news/images/Like.png' %}" alt="..."/>
                                    <p class="like_counter">{{ comment.comment_like }}</p>
                                </a>
                            </div>
                        {% endif %}

                        <p class="info" style="margin-bottom: 0;">{{ comment.author }}</p>
                        <p class="info" style="margin-bottom: 0;">{{ comment.text|safe }}</p>
                        <p style="font-size: 14px; margin-bottom: 1;">{{ comment.created_date }}</p>

                        {% if user.is_authenticated %}

                            <a class="reply" href="#reply '{{ comment.id }}'">
                                <input class="btn btn-primary"
                                        style="margin-left: 600px; margin-top: -30px; position:absolute;" type="button" value="Ответить" onmousedown="viewRDiv({{ comment.id }})">
                            </a>
                        {% else %}
                            <a class="reply" href="#log">Ответить</a>
                        {% endif %}


                    </div>
                {% endif %}

                <a name="reply '{{ comment.id }}'"></a>

                {% for replay in comment.Replies.all %}
                    <div style="margin-left: 82px;">

                        <img src="{{MEDIA_URL}}{{replay.author.image.url}}" alt="..." class="prof_pic_reply"/>
                        <div class="comment">

                            {% if user.is_authenticated %}
                                <div class="like_or_dislike_reply">
                                    <a href="{% url 'news:like_or_dislike' news_pk=items.pk comment_pk=replay.pk vote='dislike' %}">
                                        <img class="dislike" src="{% static 'news/images/Dislike.png' %}" alt="..."/>
                                        <p class="dislike_counter">{{ replay.comment_dislike }}</p>
                                    </a>
                                    <a href="{% url 'news:like_or_dislike' news_pk=items.pk comment_pk=replay.pk vote='like' %}">
                                        <img class="like" src="{% static 'news/images/Like.png' %}" alt="..."/>
                                        <p class="like_counter">{{ replay.comment_like }}</p>
                                    </a>
                                </div>
                            {% else %}
                                <div class="like_or_dislike_reply">
                                    <a href="#log">
                                        <img class="dislike" src="{% static 'news/images/Dislike.png' %}" alt="..."/>
                                        <p class="dislike_counter">{{ replay.comment_dislike }}</p>
                                    </a>
                                    <a href="#log">
                                        <img class="like" src="{% static 'news/images/Like.png' %}" alt="..."/>
                                        <p class="like_counter">{{ replay.comment_like }}</p>
                                    </a>
                                </div>
                            {% endif  %}

                            <p class="info" style="margin-bottom: 0;">{{ replay.author}}</p>
                            <p class="info" style="margin-bottom: 0;">{{ replay.text|safe }}</p>
                            <p style="margin-bottom: 0; font-size: 14px;">{{ replay.created_date }}</p>
                        </div>
                    </div>
                    </br>

                {% endfor %}

                {% if comment.parent is None %}

                    {% if user.is_authenticated %}
                        {% csrf_token %}

                            <div class="reply-form" style="display: none;" id="{{ comment.id }}">
                                <div class="reply-form-wrap">
                                    <form action="." method="post" style="display: flex; width: 100%">
                                        {% csrf_token %}
                                        <textarea class="summernote" name="text" cols="21" rows="4" required="" id="summernote"></textarea>
                                        <style>
                                            iframe.note-fullscreen {
                                                position: fixed;
                                                top: 0;
                                                left: 0;
                                                width: 100vw!important;
                                                height: 100vh!important;
                                                z-index: 4000;
                                            }
                                        </style>
                                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                        <div style="padding-left: 10px;">
                                            <input class="btn btn-primary" type="submit" value="Высказатсья">
                                        </div>
                                    </form>
                                </div>
                            </div>
                    {% endif %}

                {% endif %}

                {% empty %}
                <h4>В разделе "комментарии" пока что пусто</h4>

            {% endfor %}

        </div>
        </br>
    </div>
</div>
<script>

    function viewRDiv(a){
        document.getElementById(a).style.display = "block";
    };

  $('#first_summernote').summernote({
    placeholder: 'Hello stand alone ui',
    tabsize: 2,
    width: 654,
    height: 100,
    toolbar: [
      ['font', ['bold', 'underline','italic', 'clear']],
      ['para', ['ul', 'ol', 'paragraph']]
    ]
  });

    $('.summernote').each(function(i, obj) {
        i++;
        $(obj).summernote({
          tabsize: 2,
          width: 620,
          height: 100,
          toolbar: [
              ['font', ['bold', 'underline','italic', 'clear']],
              ['para', ['ul', 'ol', 'paragraph']],
          ],
          onChange: function() {
              $("#stage_"+i).val($("#description_"+i).code());
              //alert(i);
          }
        });
    });

</script>

{% endblock %}

news/templates/news/news_list.html
{% extends 'core/base.html' %}

{% load static %}


{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="{% static 'news/css/news.css' %}" type="text/css" rel="stylesheet" media="all">

<nav class="navbar navbar-expand-lg navbar-down bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler ml-md-auto" type="button"
                data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                {% for i in categories %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:news_in_category' i.slug %}">
                            {{ i.title }}
                        </a>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
</nav>

{% for i in news %}
    <div class="new">
        <a class="cat_item" href="{% url 'news:news_in_category' i.category.slug %}">
            {{ i.category }}
        </a>
<!--        <div class="comment_counter">-->
            <a  class="comment_counter"
                href=" {% url 'news:news_items' i.pk %}#discussion ">
                <img class="comment_img" src="{% static 'news/images/comments.png' %}" alt="..."/>
                <div class="comment_digit">{{ i.Comments.all.count }}</div>
            </a>
<!--        </div>-->
        <a class="n1" href="{% url 'news:news_items' i.pk %}">
            <div class="news_table">
                <img class="card-img-top" src="{{MEDIA_URL}}{{i.main_image.url}}" width="50%" alt="..." />
                <h3>{{ i.title }}</h3></br>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock content %}