core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

covid/urls.py
from django.urls import path
from covid.views import covid

app_name = 'covid'

urlpatterns = [
    path('', covid, name='covid'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path
from forum.views import category_list, topic_detail, topic_list, topic_filter_new, \
    topic_filter_author, topic_filter_takepart, complain


app_name = 'forum'

urlpatterns = [
    path('', category_list, name='category_list'),
    path('topic_list/<int:detail_pk>/', topic_list, name='topic_list'),
    path('topic/<int:topic_pk>/', topic_detail, name='topic_detail'),
    path('topic_filter_new/', topic_filter_new, name='topic_filter_new'),
    path('topic_filter_author/', topic_filter_author, name='topic_filter_author'),
    path('topic_filter_takepart/', topic_filter_takepart, name='topic_filter_takepart'),
    path('<int:post_pk>/complain/', complain, name='complain'),
]

news/urls.py
from django.urls import path
from news.views import news_list, news_in_category, news_items, like_or_dislike

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    path('<int:news_pk>/', news_items, name='news_items'),
    path('<int:news_pk>/<int:comment_pk>/<str:vote>', like_or_dislike, name='like_or_dislike'),
    path('<slug>/', news_in_category, name='news_in_category'),
]

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from shop.views import index, product_detail, shopping_cart, basket_add, basket_delete, checkout, user_orders


app_name = 'shop'

urlpatterns = [
    path('', index, name='index'),
    path('<int:category_id>/', index, name='category'),
    path('page<int:page>/', index, name='page'),
    path('detail/<int:product_id>/', product_detail, name='product_detail'),
    path('shopping_cart/', shopping_cart, name='shopping_cart'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket_delete/<int:product_id>/', basket_delete, name='basket_delete'),
    path('checkout/', checkout, name='checkout'),
    # path('confirm_order/', confirm_order, name='confirm_order'),
    path('order_history/', user_orders, name='user_orders'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

core/models.py
from django.db import models

core/views.py
from django.shortcuts import render, redirect
from weather.views import core_weather
from currency.views import core_kurs_dollar


def core_base(request):
    return render(request, 'core/base.html', {'core_weather': core_weather(request),
                                              'kurs_dollar': core_kurs_dollar(request)})





core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Z09-liner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="{% static 'core/css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'core/css/style.css' %}" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="{% static 'core/css/fontawesome-all.min.css' %}" rel="stylesheet">
	<!-- //Custom Theme files -->
    <!-- online-fonts -->
    <link href="//fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
    <!-- //online-fonts -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
     <link href="/examples/vendors/bootstrap-4.3/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <!-- banner -->
    <div class="inner-banner">
        <!-- header -->
        <header>
            <!--Иконка-->
            <nav class="navbar navbar-expand-lg navbar-light bg-gradient-secondary pt-3">
                <h1>
                    <a class="navbar-brand text-white" href="{% url 'core:core_base' %}">
                       <i class="far fa-copyright"></i>
                    </a>
                </h1>
                <button class="navbar-toggler ml-md-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--Навигация-->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-lg-auto text-center">
                        <!-- Контейнер ли копировать-->
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link"
							   href="{% url 'news:news_list' %}">Новости
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'used_cars_main_list' %}">Автобрахолка
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'houses_and_apartments:flat_list' %}">Квартиры
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'service:service_home' %}">Услуги
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'forum:category_list' %}">Форум
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'currency:currency' %}">{{ kurs_dollar }}</a>
                        </li>
						<li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'weather:weather' %}">{{ core_weather }}</a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'covid:covid' %}">covid</a>
                        </li>
						<li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'shop:index' %}">Магазин
                            </a>
                        </li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                        {% if user.is_authenticated %}
                            {% csrf_token %}
                            <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}</a></li>
                        <li class="nav-item  mr-3 mt-lg-0 mt-3">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                            <div><a class="nav-link" href="{% url 'users:login' %}">Login</a></div>
                        {% endif %}

                    </ul>
                </div>
                <div style="position: absolute; right: 100px; margin: 100px 0px 0px 0px;">
                    <form class="d-flex" action="{% url 'search:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="zapros" aria-label="Search" placeholder="Введите ваш запрос">
                        <button type="submit" class="btn btn-outline-dark">Искать</button>
                    </form>
                </div>
			</nav>
        </header>
    </div>

    <div class="agileits-services py-md-5 py-4">

        {% block content %}



        {% endblock content %}

    </div>

	<footer class="footer-emp bg-dark py-5">
		<div class="container">
			<div class="row footer-top">
				<div class="col-lg-4 footer-grid pr-5">
					<h2 class="footer-title border-bottom text-uppercase mb-4 pb-3">О нас</h2>
					<div class="footer-text">

						<p>Милые</p>

					</div>
				</div>
				<div class="col-lg-4 footer-grid my-lg-0 my-4">
					<h3 class="footer-title border-bottom text-uppercase mb-4 pb-3">Быстрый переход</h3>
					<ul class="links list-unstyled">
						<li>
							<a href="#">Каталог</a>
						</li>
						<li class="my-2">
							<a href="{% url 'news:news_list' %}">Новости</a>
						</li>
						<li>
							<a href="{% url 'used_cars_main_list' %}">Автобрахолка</a>
						</li>
						<li class="my-2">
							<a href="#">Дома и квартиры</a>
						</li>
						<li>
							<a href="#">Услуги</a>
						</li>
						<li class="mt-2">
							<a href="{% url 'forum:category_list' %}">Форум</a>
						</li>
                        <li class="mt-2">
							<a href="#">Барахолка</a>
						</li>
						<li class="mt-2">
							<a href="{% url 'shop:index' %}">Магазин</a>
						</li>
					</ul>


				</div>
				<div class="col-lg-4 footer-grid">
					<h3 class="footer-title border-bottom text-uppercase mb-4 pb-3">Контакты</h3>
					<div class="contact-info">
						<ul class="list-unstyled">
							<li>
								<div class="row">
									<div class="col-1">
										<i class="fas fa-map-marker"></i>
									</div>
									<div class="col-11">
										<p>Созданно при поддержке
											<span>Сашки</span>Какашки</p>
									</div>
								</div>
							</li>
							<li class="my-2">
								<div class="row">
									<div class="col-1">
										<i class="fas fa-phone"></i>
									</div>
									<div class="col-11">
										<p>8-800-555-35-35</p>
									</div>
								</div>
							</li>
							<li>
								<div class="row">
									<div class="col-1">
										<i class="fas fa-envelope"></i>
									</div>
									<div class="col-11">
										<a href="mailto:info@example.com">mail@example.com</a>
									</div>
								</div>
							</li>
						</ul>

					</div>
					<ul class="footer-social mt-md-4 mt-3">
						<li class="mx-2">
							<a href="#">
								<span class="fab fa-facebook-f"></span>
							</a>
						</li>
						<li class="mx-2">
							<a href="#">
								<span class="fab fa-twitter"></span>
							</a>
						</li>
						<li class="mx-2">
							<a href="#">
								<span class="fab fa-google-plus-g"></span>
							</a>
						</li>
						<li class="mx-2">
							<a href="#">
								<span class="fab fa-linkedin-in"></span>
							</a>
						</li>
						<li class="mx-2">
							<a href="#">
								<span class="fas fa-rss"></span>
							</a>
						</li>
						<li class="mx-2">
							<a href="#">
								<span class="fab fa-vk"></span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- //footer -->




                                        <!--    НЕ ТРОГАТЬ-->



<!-- js -->
    <script src="{% static 'core/js/jquery-2.2.3.min.js' %}"></script>
<!-- //js -->
 <!-- start-smooth-scrolling -->
    <script src="{% static 'core/js/move-top.js' %}"></script>
    <script src="{% static 'core/js/easing.js' %}"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();

                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 1000);
            });
        });
    </script>
    <!-- //end-smooth-scrolling -->
    <!-- smooth-scrolling-of-move-up -->
    <script>
        $(document).ready(function () {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <script src="{% static 'core/js/SmoothScroll.min.js' %}"></script>

    <script src="{% static 'core/js/bootstrap.js' %}"></script>
 <script src="/examples/vendors/jquery/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="/examples/vendors/bootstrap-4.3/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

</body>

</html>